server.port=8081
project-version=@project.version@
#   context-path used to set an absolute base path - invoke with url/wordle
server.servlet.context-path=/wordle
spring.web.resources.cache.cachecontrol.no-cache=true
