
name: Java CI with Maven

on:
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v6

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build and Test with Maven
        run: mvn -B clean test package

      - name: Upload JAR file
        uses: actions/upload-artifact@v6
        with:
          name: wordle-jar
          path: target/*.jar

      - name: Build and generate JaCoCo report
        run: mvn clean verify org.jacoco:jacoco-maven-plugin:report

      - name: Publish JaCoCo Report as PR comment
        uses: Madrapps/jacoco-report@v1.3.1
        with:
          paths: FDUWordle/target/site/jacoco/jacoco.xml
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70 
          min-coverage-changed-files: 70
